[package]
name = "kroyer"
version = "0.1.0"
edition = "2024"
authors = ["Atle Skaanes Ahrenfeldt <atle.skaanes@gmail.com>"]

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
image = "0.25.5"
rand = "0.9.0"
rand_chacha = "0.9.0"
primitive-types = "0.13.1"
